---
# tasks file for haproxyloadbalancer
- name: haproxy present
  package:
          name: haproxy
          state: present
- name: haproxy config
  template:
          src: "haproxy.cfg.j2"
          dest: /etc/haproxy/haproxy.cfg
  notify:
           - haproxy restart
- name: haproxy service start
  service:
          name: haproxy
          state: started
- name: firewall allow
  firewalld:
          port: "{{ proxy_port }}/tcp"
          permanent: true
          state: enabled
          immediate: yes
  ignore_errors: yes

